package com.model;

/**
 * TShoucang generated by MyEclipse Persistence Tools
 */

public class TShoucang implements java.io.Serializable
{

	private Integer id;
	private Integer yinyueId;
	private String shijian;
	private Integer huiyuanId;
	
	private TYinyue yinyue;

	public Integer getId()
	{
		return id;
	}

	public void setId(Integer id)
	{
		this.id = id;
	}

	public Integer getYinyueId()
	{
		return yinyueId;
	}

	public void setYinyueId(Integer yinyueId)
	{
		this.yinyueId = yinyueId;
	}

	public String getShijian()
	{
		return shijian;
	}

	public void setShijian(String shijian)
	{
		this.shijian = shijian;
	}

	public Integer getHuiyuanId()
	{
		return huiyuanId;
	}

	public void setHuiyuanId(Integer huiyuanId)
	{
		this.huiyuanId = huiyuanId;
	}

	public TYinyue getYinyue()
	{
		return yinyue;
	}

	public void setYinyue(TYinyue yinyue)
	{
		this.yinyue = yinyue;
	}
	
		
}